name: Merge Release Branch and Create Release

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: version for release
      override:
        type: boolean
        description: Merge even if PR checks are not passing (do this at your peril)?
        default: false

jobs:
  merge_release_branch_and_create_release:
    runs-on: ubuntu-latest

    steps:

      - name: Display inputs
        run: echo "${{ github.event.inputs.version }}"

      - name: Check PAT token is still valid
        run: |
          gh workflow list --repo "$GITHUB_REPOSITORY_OWNER/flood-service"
        env:
          # if this fails the create/regenerate classic PAT and then populate it using `gh secret set GH_WORKFLOW`
          GH_TOKEN: ${{ secrets.GH_WORKFLOW }}

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: development
          fetch-depth: 0

      - name: Set up Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Setup version env vars
        run: |
          version=${{ github.event.inputs.version }}
          echo VERSION=$version >> "$GITHUB_ENV"
          echo RELEASE_BRANCH="release/$version" >> "$GITHUB_ENV"
          echo TAG_VERSION="v$version" >> "$GITHUB_ENV"
          echo RELEASE_NOTES_FILE="./release-docs/CFF-${version}.md" >> "$GITHUB_ENV"
          echo OVERRIDE=${{ github.event.inputs.override }} >> "$GITHUB_ENV"

      - name: Check Master PR exists and is mergeable
        run: |
          base=master
          pr_id=$(gh pr list --base "$base" --head "${RELEASE_BRANCH}" --limit 1 --json number --state open --jq '.[] | .number')
          if [ $pr_id -eq 0 ] ; then
            echo "Error: PR for ${RELEASE_BRANCH} > $base does not exist."
            exit 1
          fi
          merge_status=$(gh pr view --json mergeStateStatus --jq '.mergeStateStatus' $pr_id ) 
          if [[ "$merge_status" != 'CLEAN' ]] && ! $OVERRIDE ; then
            echo "Error: PR for ${RELEASE_BRANCH} > $base ($pr_id) does not have merge status of is CLEAN and probably needs approval "
            exit 1
          fi
          echo MASTER_PR=$pr_id >> "$GITHUB_ENV"
        env:
          GH_TOKEN: ${{ secrets.GH_WORKFLOW }}

      - name: Check Development PR exists and is mergeable
        run: |
          base=development
          pr_id=$(gh pr list --base "$base" --head "${RELEASE_BRANCH}" --limit 1 --json number --state open --jq '.[] | .number')
          if [ $pr_id -eq 0 ] ; then
            echo "Error: PR for ${RELEASE_BRANCH} > $base does not exist."
            exit 1
          fi
          merge_status=$(gh pr view --json mergeStateStatus --jq '.mergeStateStatus' $pr_id ) 
          if [[ "$merge_status" != 'CLEAN' ]] && ! $OVERRIDE ; then
            echo "Error: PR for ${RELEASE_BRANCH} > $base ($pr_id) does not have merge status of is CLEAN and probably needs approval "
            exit 1
          fi
          echo DEVELOPMENT_PR=$pr_id >> "$GITHUB_ENV"
        env:
          GH_TOKEN: ${{ secrets.GH_WORKFLOW }}

      - name: Merge PRs
        run: |
          gh pr comment --body "Merged by merge.yml workflow" $MASTER_PR
          gh pr merge --rebase $MASTER_PR
          gh pr comment --body "Merged by merge.yml workflow" $DEVELOPMENT_PR
          gh pr merge --rebase --delete-branch $DEVELOPMENT_PR
        env:
          GH_TOKEN: ${{ secrets.GH_WORKFLOW }}

      - name: Create Release
        run: gh release create $TAG_VERSION --title "Release $VERSION" --notes "[release notes](/$RELEASE_NOTES_FILE)"
        env:
          GH_TOKEN: ${{ secrets.GH_WORKFLOW }}

      - name: Trigger Merge Release Branch for flood-service
        run: |
          echo "trigger commented out"
          # gh workflow run --repo  "$GITHUB_REPOSITORY_OWNER/flood-service" merge.yml -f version="$VERSION"
        env:
          # use PAT token with repo scope (github.token didn't work)
          GH_TOKEN: ${{ secrets.GH_WORKFLOW }}
